vmmssh wait for vm up

diff --git a/hvnalias b/hvnalias
--- a/hvnalias
+++ b/hvnalias
@@ -434,7 +434,18 @@ alias hn='/home/hvn/py3/bin/python /home/hvn/me/pyfml/exercises/ex9/hnsotw.py'
 
 vmmssh () {
   vmname=$1
-  (vmctl status $vmname 2>&1 | grep -q running) || doas vmctl start $vmname
-  ip=$(vmctl status $vmname | grep $vmname | column -t | cut -d ' ' -f1)
-  ssh -v root@"100.64.${ip}.3"
+  if [ -n "$vmname" ]; then
+    echo "$vmnname"
+    (vmctl status "$vmname" 2>&1 | grep -q running) || (doas vmctl start "$vmname")
+    octet=$(vmctl status "$vmname" | grep "$vmname" | column -t | cut -d ' ' -f1)
+    vmip="100.64.${octet}.3"
+    until nc -z -w1 "$vmip" 22; do
+      printf .
+      sleep 1
+    done
+    ssh -v root@"$vmip"
+  else
+    echo "Missing vmnname"
+    vmctl status
+  fi
 }
