on Ubuntu there is only virtualenv

diff --git a/py2env b/py2env
--- a/py2env
+++ b/py2env
@@ -1,13 +1,14 @@
 #!/bin/bash
 
 set -x
+CMD=virtualenv
 if [ ! -e ~/python2 ]; then
-    if (which virtualenv-2.7 2>&1>/dev/null); then
-         virtualenv-2.7 ~/python2
+    if (which $CMD 2>&1>/dev/null); then
+         $CMD ~/python2
          source ~/python2/bin/activate
          pip install -r ~/.py2req.txt
     else
-        echo 'Missing virtualenv-2.7'; exit 1
+        echo "Missing $CMD"; exit 1
     fi
 else
   echo ~/python2 exists
